"""Emit src/riftgate_zones.h: the campaign's riftgate zones in the game's own order with their act.

The riftgate map's master table (records/ui/riftgatemap/riftgate_mastertable.dbr, Region001ZoneList) is a single
flat list -- the game has no act field -- but it is authored in progression order and every zone record's name is
prefixed with the world chunk letter (riftgatemap1a_* = Act 1 chunks 0A..., 1b = Act 2, 1f = Act 3, 1g = Act 4).
The mod matches a live map icon to a zone by the localized ZoneNameTag ("Devil's Crossing Rift"), which is the
icon's name. Rerun after a game patch: uv run tools/gen_riftgate_zones.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arz

ACT_BY_LETTER = {"a": 1, "b": 2, "f": 3, "g": 4}
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    d, strings, recs = arz.load()
    by_name = {path.lower(): (off, csz, dsz) for path, _cls, off, csz, dsz in recs}
    master = by_name["records/ui/riftgatemap/riftgate_mastertable.dbr"]
    fields = arz.decode(d, strings, *master)
    zones = fields["Region001ZoneList"]
    out = ["// Generated by tools/gen_riftgate_zones.py from database.arz -- do not edit. The riftgate map's zone list",
           "// in the game's own (progression) order; act = the zone record's chunk letter (1a/1b/1f/1g).",
           "#pragma once", "namespace gd::riftgate_zones {",
           "struct Zone { const char* tag; int act; int order; };",
           "inline constexpr Zone kZones[] = {"]
    n = 0
    for order, path in enumerate(zones):
        rec = by_name.get(path.lower())
        if not rec:
            print("missing zone record", path, file=sys.stderr); continue
        f = arz.decode(d, strings, *rec)
        tag = f.get("ZoneNameTag", [""])[0]
        base = os.path.basename(path)
        letter = base[len("riftgatemap1"):len("riftgatemap1") + 1] if base.startswith("riftgatemap1") else ""
        act = ACT_BY_LETTER.get(letter, 0)
        if not tag or not act:
            print("unclassified zone", path, tag, file=sys.stderr)
        out.append(f'  {{"{tag}", {act}, {order}}},   // {base}')
        n += 1
    out += ["};", f"inline constexpr int kActs = {max(ACT_BY_LETTER.values())};", "}  // namespace gd::riftgate_zones", ""]
    dst = os.path.join(ROOT, "src", "riftgate_zones.h")
    open(dst, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"wrote {dst} with {n} zones")


if __name__ == "__main__":
    main()
