"""Emit src/shrine_table.h: every devotion shrine of the campaign map with the chunk that holds it.

Source: world001.map's region table (tools/gdmap/mapfile.py) -- each chunk record names at most one devotion
shrine record (records/ui/riftgatemap/devotionshrines/*.dbr, the world map's icon) -- plus that icon record's
FileDescription (the area name the map shows), corrupted/ruined flags, and the chunk's world-map location
record (-> the riftgate zone -> the act). The shrine's position is approximated by the chunk's world offset
(chunk origin); the chunk's own GUID is carried as the candidate key for Player::Get(Discovered)ShrineUIDs --
to be confirmed live (dev route /shrines). Rerun after a game patch: uv run tools/gen_shrines.py
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import arz
from gdmap.mapfile import WorldMap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    d, strings, recs = arz.load()
    by_name = {path.lower(): (off, csz, dsz) for path, _cls, off, csz, dsz in recs}
    wm = WorldMap()
    rows = []
    for r in wm.regions:
        if not r.shrine:
            continue
        rec = by_name.get(f"records/ui/riftgatemap/devotionshrines/{r.shrine}.dbr".lower())
        f = arz.decode(d, strings, *rec) if rec else {}
        desc = f.get("FileDescription", [""])[0]
        corrupted = bool(f.get("corruptedShrine", [False])[0])
        ruined = bool(f.get("ruinedShrine", [False])[0])
        zone_tag = ""
        if r.location:
            zrec = by_name.get(f"records/ui/riftgatemap/locations/{r.location}.dbr".lower())
            if zrec:
                zone_tag = arz.decode(d, strings, *zrec).get("ZoneNameTag", [""])[0]
        guid = ", ".join(f"0x{b:02x}" for b in r.guid)
        ox, oy, oz = r.world_offset
        rows.append(f'  {{"{r.shrine}", "{desc}", "{zone_tag}", "{r.name}", {ox}, {oy}, {oz}, {str(corrupted).lower()}, {str(ruined).lower()}, {{{guid}}}}},')
    out = ["// Generated by tools/gen_shrines.py from world001.map + database.arz -- do not edit.",
           "// One row per chunk that carries a devotion shrine: the map icon record, the area name the map shows,",
           "// the riftgate zone tag of the chunk's location, the chunk name, the chunk's world origin (the shrine's",
           "// position to chunk precision), the icon's corrupted/ruined flags, and the chunk GUID (candidate UID).",
           "#pragma once", "#include <cstdint>", "namespace gd::shrine_table {",
           "struct Shrine { const char* icon; const char* area; const char* zone_tag; const char* chunk; int x, y, z; bool corrupted, ruined; uint8_t guid[16]; };",
           "inline constexpr Shrine kShrines[] = {"] + rows + ["};", "}  // namespace gd::shrine_table", ""]
    dst = os.path.join(ROOT, "src", "shrine_table.h")
    open(dst, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"wrote {dst} with {len(rows)} shrines")


if __name__ == "__main__":
    main()
