// GENERATED by tools/gen_names.py -- do not edit
#pragma once
namespace gd::names {
// protected: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::LocalizationManager::GetText(char const * __ptr64) __ptr64
inline constexpr const char* LocalizationManager_GetText_DLL = "Engine.dll";
inline constexpr const char* LocalizationManager_GetText = "?GetText@LocalizationManager@GAME@@IEAA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@PEBD@Z";
// public: void __cdecl GAME::Display::Update(void) __ptr64
inline constexpr const char* Display_Update_DLL = "Engine.dll";
inline constexpr const char* Display_Update = "?Update@Display@GAME@@QEAAXXZ";
// public: void __cdecl GAME::Engine::Update(class GAME::Sphere const * __ptr64,class GAME::WorldFrustum const * __ptr64,bool,class GAME::WorldFrustum const * __ptr64) __ptr64
inline constexpr const char* Engine_Update_DLL = "Engine.dll";
inline constexpr const char* Engine_Update = "?Update@Engine@GAME@@QEAAXPEBVSphere@2@PEBVWorldFrustum@2@_N1@Z";
// public: void __cdecl GAME::GameEngine::Update(int) __ptr64
inline constexpr const char* GameEngine_Update_DLL = "Game.dll";
inline constexpr const char* GameEngine_Update = "?Update@GameEngine@GAME@@QEAAXH@Z";
// public: class GAME::Player * __ptr64 __cdecl GAME::GameEngine::GetMainPlayer(void)const __ptr64
inline constexpr const char* GameEngine_GetMainPlayer_DLL = "Game.dll";
inline constexpr const char* GameEngine_GetMainPlayer = "?GetMainPlayer@GameEngine@GAME@@QEBAPEAVPlayer@2@XZ";
// public: class GAME::GameCamera * __ptr64 __cdecl GAME::GameEngine::GetCamera(void) __ptr64
inline constexpr const char* GameEngine_GetCamera_DLL = "Game.dll";
inline constexpr const char* GameEngine_GetCamera = "?GetCamera@GameEngine@GAME@@QEAAPEAVGameCamera@2@XZ";
// public: void __cdecl GAME::GameEngine::GetAllTargetsInRadius(unsigned int,class GAME::FactionPack const & __ptr64,class GAME::WorldVec3 const & __ptr64,float,class mem::vector<unsigned int> & __ptr64,unsigned int,bool)co
inline constexpr const char* GameEngine_GetAllTargetsInRadius_DLL = "Game.dll";
inline constexpr const char* GameEngine_GetAllTargetsInRadius = "?GetAllTargetsInRadius@GameEngine@GAME@@QEBAXIAEBVFactionPack@2@AEBVWorldVec3@2@MAEAV?$vector@I@mem@@I_N@Z";
// public: virtual void __cdecl GAME::ControllerPlayer::Update(int) __ptr64
inline constexpr const char* ControllerPlayer_Update_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_Update = "?Update@ControllerPlayer@GAME@@UEAAXH@Z";
// public: void __cdecl GAME::ControllerPlayer::SetCombatEnemy(unsigned int) __ptr64
inline constexpr const char* ControllerPlayer_SetCombatEnemy_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_SetCombatEnemy = "?SetCombatEnemy@ControllerPlayer@GAME@@QEAAXI@Z";
// public: unsigned int __cdecl GAME::ControllerPlayer::GetCombatEnemy(void)const __ptr64
inline constexpr const char* ControllerPlayer_GetCombatEnemy_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_GetCombatEnemy = "?GetCombatEnemy@ControllerPlayer@GAME@@QEBAIXZ";
// public: void __cdecl GAME::ControllerPlayer::ClearTarget(void) __ptr64
inline constexpr const char* ControllerPlayer_ClearTarget_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_ClearTarget = "?ClearTarget@ControllerPlayer@GAME@@QEAAXXZ";
// public: void __cdecl GAME::ControllerPlayer::FaceTarget(unsigned int) __ptr64
inline constexpr const char* ControllerPlayer_FaceTarget_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_FaceTarget = "?FaceTarget@ControllerPlayer@GAME@@QEAAXI@Z";
// public: bool __cdecl GAME::ControllerPlayer::HandleActionFromJoystick(class GAME::WorldVec3 const & __ptr64,bool) __ptr64
inline constexpr const char* ControllerPlayer_HandleActionFromJoystick_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_HandleActionFromJoystick = "?HandleActionFromJoystick@ControllerPlayer@GAME@@QEAA_NAEBVWorldVec3@2@_N@Z";
// public: bool __cdecl GAME::ControllerPlayer::HandleActionFromMouse(bool,bool,bool,bool,class GAME::WorldVec3 const & __ptr64,unsigned int & __ptr64,bool * __ptr64) __ptr64
inline constexpr const char* ControllerPlayer_HandleActionFromMouse_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_HandleActionFromMouse = "?HandleActionFromMouse@ControllerPlayer@GAME@@QEAA_N_N000AEBVWorldVec3@2@AEAIPEA_N@Z";
// public: void __cdecl GAME::ControllerPlayer::SetControllerDirection(class GAME::Vec3 const & __ptr64) __ptr64
inline constexpr const char* ControllerPlayer_SetControllerDirection_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_SetControllerDirection = "?SetControllerDirection@ControllerPlayer@GAME@@QEAAXAEBVVec3@2@@Z";
// public: void __cdecl GAME::ControllerPlayer::GetControllerDirection(class GAME::Vec3 & __ptr64) __ptr64
inline constexpr const char* ControllerPlayer_GetControllerDirection_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_GetControllerDirection = "?GetControllerDirection@ControllerPlayer@GAME@@QEAAXAEAVVec3@2@@Z";
// public: void __cdecl GAME::ControllerPlayer::SetControllerMovementLength(float) __ptr64
inline constexpr const char* ControllerPlayer_SetControllerMovementLength_DLL = "Game.dll";
inline constexpr const char* ControllerPlayer_SetControllerMovementLength = "?SetControllerMovementLength@ControllerPlayer@GAME@@QEAAXM@Z";
// public: class GAME::WorldCoords __cdecl GAME::Entity::GetCoords(void)const __ptr64
inline constexpr const char* Entity_GetCoords_DLL = "Engine.dll";
inline constexpr const char* Entity_GetCoords = "?GetCoords@Entity@GAME@@QEBA?AVWorldCoords@2@XZ";
// public: class GAME::Region * __ptr64 __cdecl GAME::Entity::GetRegion(void)const __ptr64
inline constexpr const char* Entity_GetRegion_DLL = "Engine.dll";
inline constexpr const char* Entity_GetRegion = "?GetRegion@Entity@GAME@@QEBAPEAVRegion@2@XZ";
// protected: virtual class GAME::WorldCoords __cdecl GAME::Character::GetFootCoords(bool) __ptr64
inline constexpr const char* Character_GetFootCoords_DLL = "Game.dll";
inline constexpr const char* Character_GetFootCoords = "?GetFootCoords@Character@GAME@@MEAA?AVWorldCoords@2@_N@Z";
// public: double const __cdecl GAME::Character::GetCurrentLife(void)const __ptr64
inline constexpr const char* Character_GetCurrentLife_DLL = "Game.dll";
inline constexpr const char* Character_GetCurrentLife = "?GetCurrentLife@Character@GAME@@QEBA?BNXZ";
// public: float const __cdecl GAME::Character::GetLifeLimit(void)const __ptr64
inline constexpr const char* Character_GetLifeLimit_DLL = "Game.dll";
inline constexpr const char* Character_GetLifeLimit = "?GetLifeLimit@Character@GAME@@QEBA?BMXZ";
// public: unsigned short const * __ptr64 __cdecl GAME::Player::GetPlayerName(void)const __ptr64
inline constexpr const char* Player_GetPlayerName_DLL = "Game.dll";
inline constexpr const char* Player_GetPlayerName = "?GetPlayerName@Player@GAME@@QEBAPEBGXZ";
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64 __cdecl GAME::Region::GetName(void)const __ptr64
inline constexpr const char* Region_GetName_DLL = "Engine.dll";
inline constexpr const char* Region_GetName = "?GetName@Region@GAME@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ";
// public: static class GAME::NavManager * __ptr64 __cdecl GAME::Singleton<class GAME::NavManager>::Get(void)
inline constexpr const char* NavManager_Get_DLL = "Engine.dll";
inline constexpr const char* NavManager_Get = "?Get@?$Singleton@VNavManager@GAME@@@GAME@@SAPEAVNavManager@2@XZ";
// public: bool __cdecl GAME::NavManager::IsPointOnPathMesh(class GAME::WorldVec3 const & __ptr64) __ptr64
inline constexpr const char* NavManager_IsPointOnPathMesh_DLL = "Engine.dll";
inline constexpr const char* NavManager_IsPointOnPathMesh = "?IsPointOnPathMesh@NavManager@GAME@@QEAA_NAEBVWorldVec3@2@@Z";
// public: enum GAME::NavResult __cdecl GAME::NavManager::FindStraightMovePoint(class GAME::WorldVec3 const & __ptr64,class GAME::WorldVec3 const & __ptr64,class GAME::WorldVec3 & __ptr64) __ptr64
inline constexpr const char* NavManager_FindStraightMovePoint_DLL = "Engine.dll";
inline constexpr const char* NavManager_FindStraightMovePoint = "?FindStraightMovePoint@NavManager@GAME@@QEAA?AW4NavResult@2@AEBVWorldVec3@2@0AEAV42@@Z";
// public: enum GAME::NavResult __cdecl GAME::NavManager::FindClosestPointOnPathMesh(class GAME::WorldVec3 const & __ptr64,class GAME::WorldVec3 & __ptr64,float) __ptr64
inline constexpr const char* NavManager_FindClosestPointOnPathMesh_DLL = "Engine.dll";
inline constexpr const char* NavManager_FindClosestPointOnPathMesh = "?FindClosestPointOnPathMesh@NavManager@GAME@@QEAA?AW4NavResult@2@AEBVWorldVec3@2@AEAV42@M@Z";
// public: __cdecl GAME::WorldVec3::WorldVec3(class GAME::Region * __ptr64,class GAME::Vec3 const & __ptr64) __ptr64
inline constexpr const char* WorldVec3_ctor_DLL = "Engine.dll";
inline constexpr const char* WorldVec3_ctor = "??0WorldVec3@GAME@@QEAA@PEAVRegion@1@AEBVVec3@1@@Z";
// public: class GAME::Vec3 __cdecl GAME::WorldVec3::GetWorldPosition(void)const __ptr64
inline constexpr const char* WorldVec3_GetWorldPosition_DLL = "Engine.dll";
inline constexpr const char* WorldVec3_GetWorldPosition = "?GetWorldPosition@WorldVec3@GAME@@QEBA?AVVec3@2@XZ";
// public: class GAME::Region * __ptr64 __cdecl GAME::WorldVec3::GetRegion(void)const __ptr64
inline constexpr const char* WorldVec3_GetRegion_DLL = "Engine.dll";
inline constexpr const char* WorldVec3_GetRegion = "?GetRegion@WorldVec3@GAME@@QEBAPEAVRegion@2@XZ";
// public: class GAME::Vec3 const & __ptr64 __cdecl GAME::WorldVec3::GetRegionPosition(void)const __ptr64
inline constexpr const char* WorldVec3_GetRegionPosition_DLL = "Engine.dll";
inline constexpr const char* WorldVec3_GetRegionPosition = "?GetRegionPosition@WorldVec3@GAME@@QEBAAEBVVec3@2@XZ";
// public: bool __cdecl GAME::WorldVec3::PutOnFloor(void) __ptr64
inline constexpr const char* WorldVec3_PutOnFloor_DLL = "Engine.dll";
inline constexpr const char* WorldVec3_PutOnFloor = "?PutOnFloor@WorldVec3@GAME@@QEAA_NXZ";
// public: class GAME::Coords __cdecl GAME::WorldCoords::GetRegionCoords(void)const __ptr64
inline constexpr const char* WorldCoords_GetRegionCoords_DLL = "Engine.dll";
inline constexpr const char* WorldCoords_GetRegionCoords = "?GetRegionCoords@WorldCoords@GAME@@QEBA?AVCoords@2@XZ";
// public: float __cdecl GAME::WorldCamera::GetCameraYaw(void)const __ptr64
inline constexpr const char* WorldCamera_GetCameraYaw_DLL = "Engine.dll";
inline constexpr const char* WorldCamera_GetCameraYaw = "?GetCameraYaw@WorldCamera@GAME@@QEBAMXZ";
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64 __cdecl GAME::Engine::GetAreaNameTag(void)const __ptr64
inline constexpr const char* Engine_GetAreaNameTag_DLL = "Engine.dll";
inline constexpr const char* Engine_GetAreaNameTag = "?GetAreaNameTag@Engine@GAME@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ";
// public: void __cdecl GAME::World::Update(class mem::vector<class GAME::Sphere> const & __ptr64,class mem::vector<class GAME::WorldFrustum> const & __ptr64) __ptr64
inline constexpr const char* World_Update_DLL = "Engine.dll";
inline constexpr const char* World_Update = "?Update@World@GAME@@QEAAXAEBV?$vector@VSphere@GAME@@@mem@@AEBV?$vector@VWorldFrustum@GAME@@@4@@Z";
// public: void __cdecl GAME::World::GetEntitiesInSphere(class mem::vector<class GAME::Entity * __ptr64> & __ptr64,class GAME::Region * __ptr64,class GAME::Sphere const & __ptr64,bool,enum GAME::EntityListType)const __ptr64
inline constexpr const char* World_GetEntitiesInSphere_DLL = "Engine.dll";
inline constexpr const char* World_GetEntitiesInSphere = "?GetEntitiesInSphere@World@GAME@@QEBAXAEAV?$vector@PEAVEntity@GAME@@@mem@@PEAVRegion@2@AEBVSphere@2@_NW4EntityListType@2@@Z";
// public: bool __cdecl GAME::Engine::GetEntitiesInPriorFrameFrustum(class mem::vector<class GAME::Entity * __ptr64> & __ptr64) __ptr64
inline constexpr const char* Engine_GetEntitiesInPriorFrameFrustum_DLL = "Engine.dll";
inline constexpr const char* Engine_GetEntitiesInPriorFrameFrustum = "?GetEntitiesInPriorFrameFrustum@Engine@GAME@@QEAA_NAEAV?$vector@PEAVEntity@GAME@@@mem@@@Z";
// public: void __cdecl GAME::Region::GetEntitiesInSphere(class mem::vector<class GAME::Entity * __ptr64> & __ptr64,class GAME::Sphere const & __ptr64,bool,enum GAME::EntityListType) __ptr64
inline constexpr const char* Region_GetEntitiesInSphere_DLL = "Engine.dll";
inline constexpr const char* Region_GetEntitiesInSphere = "?GetEntitiesInSphere@Region@GAME@@QEAAXAEAV?$vector@PEAVEntity@GAME@@@mem@@AEBVSphere@2@_NW4EntityListType@2@@Z";
// public: unsigned int __cdecl GAME::Object::GetObjectId(void)const __ptr64
inline constexpr const char* Object_GetObjectId_DLL = "Engine.dll";
inline constexpr const char* Object_GetObjectId = "?GetObjectId@Object@GAME@@QEBAIXZ";
// public: class GAME::ABBox const & __ptr64 __cdecl GAME::Entity::GetRegionBoundingBox(bool)const __ptr64
inline constexpr const char* Entity_GetRegionBoundingBox_DLL = "Engine.dll";
inline constexpr const char* Entity_GetRegionBoundingBox = "?GetRegionBoundingBox@Entity@GAME@@QEBAAEBVABBox@2@_N@Z";
// public: char const * __ptr64 __cdecl GAME::Object::GetObjectName(void)const __ptr64
inline constexpr const char* Object_GetObjectName_DLL = "Engine.dll";
inline constexpr const char* Object_GetObjectName = "?GetObjectName@Object@GAME@@QEBAPEBDXZ";
// public: virtual class GAME::RTTI_ClassInfo const & __ptr64 __cdecl GAME::Object::GetRTTIClassInfo(void)const __ptr64
inline constexpr const char* Object_GetRTTIClassInfo_DLL = "Engine.dll";
inline constexpr const char* Object_GetRTTIClassInfo = "?GetRTTIClassInfo@Object@GAME@@UEBAAEBVRTTI_ClassInfo@2@XZ";
// public: static class GAME::RTTI_ClassInfo const & __ptr64 __cdecl GAME::Entity::GetStaticClassInfo(void)
inline constexpr const char* Entity_GetStaticClassInfo_DLL = "Engine.dll";
inline constexpr const char* Entity_GetStaticClassInfo = "?GetStaticClassInfo@Entity@GAME@@SAAEBVRTTI_ClassInfo@2@XZ";
// public: static class GAME::RTTI_ClassInfo const & __ptr64 __cdecl GAME::Character::GetStaticClassInfo(void)
inline constexpr const char* Character_GetStaticClassInfo_DLL = "Game.dll";
inline constexpr const char* Character_GetStaticClassInfo = "?GetStaticClassInfo@Character@GAME@@SAAEBVRTTI_ClassInfo@2@XZ";
// public: static class GAME::RTTI_ClassInfo const & __ptr64 __cdecl GAME::Monster::GetStaticClassInfo(void)
inline constexpr const char* Monster_GetStaticClassInfo_DLL = "Game.dll";
inline constexpr const char* Monster_GetStaticClassInfo = "?GetStaticClassInfo@Monster@GAME@@SAAEBVRTTI_ClassInfo@2@XZ";
// public: static class GAME::RTTI_ClassInfo const & __ptr64 __cdecl GAME::Npc::GetStaticClassInfo(void)
inline constexpr const char* Npc_GetStaticClassInfo_DLL = "Game.dll";
inline constexpr const char* Npc_GetStaticClassInfo = "?GetStaticClassInfo@Npc@GAME@@SAAEBVRTTI_ClassInfo@2@XZ";
// public: static class GAME::RTTI_ClassInfo const & __ptr64 __cdecl GAME::Player::GetStaticClassInfo(void)
inline constexpr const char* Player_GetStaticClassInfo_DLL = "Game.dll";
inline constexpr const char* Player_GetStaticClassInfo = "?GetStaticClassInfo@Player@GAME@@SAAEBVRTTI_ClassInfo@2@XZ";
// public: void __cdecl GAME::Character::GetCurrentAttackTarget(unsigned int & __ptr64,class GAME::WorldVec3 & __ptr64,unsigned int & __ptr64) __ptr64
inline constexpr const char* Character_GetCurrentAttackTarget_DLL = "Game.dll";
inline constexpr const char* Character_GetCurrentAttackTarget = "?GetCurrentAttackTarget@Character@GAME@@QEAAXAEAIAEAVWorldVec3@2@0@Z";
// public: virtual bool __cdecl GAME::Character::IsAlive(void)const __ptr64
inline constexpr const char* Character_IsAlive_DLL = "Game.dll";
inline constexpr const char* Character_IsAlive = "?IsAlive@Character@GAME@@UEBA_NXZ";
// public: class GAME::FactionManager * __ptr64 __cdecl GAME::GameEngine::GetFactionManager(void) __ptr64
inline constexpr const char* GameEngine_GetFactionManager_DLL = "Game.dll";
inline constexpr const char* GameEngine_GetFactionManager = "?GetFactionManager@GameEngine@GAME@@QEAAPEAVFactionManager@2@XZ";
// public: bool __cdecl GAME::FactionManager::IsFoe(unsigned int,unsigned int,bool) __ptr64
inline constexpr const char* FactionManager_IsFoe_DLL = "Game.dll";
inline constexpr const char* FactionManager_IsFoe = "?IsFoe@FactionManager@GAME@@QEAA_NII_N@Z";
// public: void __cdecl GAME::Conversation::GetText(class GAME::ConversationStep const * __ptr64,enum GAME::Character_Gender,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocato
inline constexpr const char* Conversation_GetText_DLL = "Game.dll";
inline constexpr const char* Conversation_GetText = "?GetText@Conversation@GAME@@QEBAXPEBVConversationStep@2@W4Character_Gender@2@AEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z";
// private: void __cdecl GAME::Conversation::GetSteps(class GAME::ConversationStep * __ptr64,class mem::vector<class GAME::ConversationStep * __ptr64> & __ptr64) __ptr64
inline constexpr const char* Conversation_GetSteps_DLL = "Game.dll";
inline constexpr const char* Conversation_GetSteps = "?GetSteps@Conversation@GAME@@AEAAXPEAVConversationStep@2@AEAV?$vector@PEAVConversationStep@GAME@@@mem@@@Z";
// public: class GAME::ConversationStep * __ptr64 __cdecl GAME::Conversation::GetRoot(void) __ptr64
inline constexpr const char* Conversation_GetRoot_DLL = "Game.dll";
inline constexpr const char* Conversation_GetRoot = "?GetRoot@Conversation@GAME@@QEAAPEAVConversationStep@2@XZ";
// public: enum GAME::ConversationStep::Type __cdecl GAME::ConversationStep::GetType(void)const __ptr64
inline constexpr const char* ConversationStep_GetType_DLL = "Game.dll";
inline constexpr const char* ConversationStep_GetType = "?GetType@ConversationStep@GAME@@QEBA?AW4Type@12@XZ";
// public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GAME::ConversationStep::GetTypeTag(void)const __ptr64
inline constexpr const char* ConversationStep_GetTypeTag_DLL = "Game.dll";
inline constexpr const char* ConversationStep_GetTypeTag = "?GetTypeTag@ConversationStep@GAME@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ";
// public: bool __cdecl GAME::ConversationStep::IsAvailable(void)const __ptr64
inline constexpr const char* ConversationStep_IsAvailable_DLL = "Game.dll";
inline constexpr const char* ConversationStep_IsAvailable = "?IsAvailable@ConversationStep@GAME@@QEBA_NXZ";
// public: bool __cdecl GAME::ConversationStep::IsUsed(void)const __ptr64
inline constexpr const char* ConversationStep_IsUsed_DLL = "Game.dll";
inline constexpr const char* ConversationStep_IsUsed = "?IsUsed@ConversationStep@GAME@@QEBA_NXZ";
// public: class GAME::ConversationStep * __ptr64 __cdecl GAME::ConversationStep::GetParent(void)const __ptr64
inline constexpr const char* ConversationStep_GetParent_DLL = "Game.dll";
inline constexpr const char* ConversationStep_GetParent = "?GetParent@ConversationStep@GAME@@QEBAPEAV12@XZ";
// public: class mem::vector<class GAME::ConversationStep * __ptr64> const & __ptr64 __cdecl GAME::ConversationStep::GetSteps(void)const __ptr64
inline constexpr const char* ConversationStep_GetSteps_DLL = "Game.dll";
inline constexpr const char* ConversationStep_GetSteps = "?GetSteps@ConversationStep@GAME@@QEBAAEBV?$vector@PEAVConversationStep@GAME@@@mem@@XZ";
// public: enum GAME::ConversationStep::Flag __cdecl GAME::ConversationStep::GetFlags(void)const __ptr64
inline constexpr const char* ConversationStep_GetFlags_DLL = "Game.dll";
inline constexpr const char* ConversationStep_GetFlags = "?GetFlags@ConversationStep@GAME@@QEBA?AW4Flag@12@XZ";
// public: class GAME::Conversation * __ptr64 __cdecl GAME::Character::GetConversation(void)const __ptr64
inline constexpr const char* Character_GetConversation_DLL = "Game.dll";
inline constexpr const char* Character_GetConversation = "?GetConversation@Character@GAME@@QEBAPEAVConversation@2@XZ";
// public: virtual class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::Monster::GetGameDescription(bool,bool)const __ptr64
inline constexpr const char* Monster_GetGameDescription_DLL = "Game.dll";
inline constexpr const char* Monster_GetGameDescription = "?GetGameDescription@Monster@GAME@@UEBA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@_N0@Z";
// public: virtual class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::Npc::GetRolloverDescription(void)const __ptr64
inline constexpr const char* Npc_GetRolloverDescription_DLL = "Game.dll";
inline constexpr const char* Npc_GetRolloverDescription = "?GetRolloverDescription@Npc@GAME@@UEBA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@XZ";
// public: class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::Player::GetRolloverDescription(void)const __ptr64
inline constexpr const char* Player_GetRolloverDescription_DLL = "Game.dll";
inline constexpr const char* Player_GetRolloverDescription = "?GetRolloverDescription@Player@GAME@@QEBA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@XZ";
// public: virtual class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > __cdecl GAME::Item::GetGameDescription(bool,bool)const __ptr64
inline constexpr const char* Item_GetGameDescription_DLL = "Game.dll";
inline constexpr const char* Item_GetGameDescription = "?GetGameDescription@Item@GAME@@UEBA?AV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@_N0@Z";
// const GAME::Object::`vftable'
inline constexpr const char* Object_vftable_DLL = "Engine.dll";
inline constexpr const char* Object_vftable = "??_7Object@GAME@@6B@";
// public: class GAME::Vec2 __cdecl GAME::WorldCamera::Project(class GAME::WorldVec3 const & __ptr64,class GAME::Viewport const & __ptr64)const __ptr64
inline constexpr const char* WorldCamera_Project_DLL = "Engine.dll";
inline constexpr const char* WorldCamera_Project = "?Project@WorldCamera@GAME@@QEBA?AVVec2@2@AEBVWorldVec3@2@AEBVViewport@2@@Z";
// public: __cdecl GAME::Viewport::Viewport(int,int,int,int) __ptr64
inline constexpr const char* Viewport_ctor_DLL = "Engine.dll";
inline constexpr const char* Viewport_ctor = "??0Viewport@GAME@@QEAA@HHHH@Z";
// public: void __cdecl GAME::Engine::ProcessUserInput(void) __ptr64
inline constexpr const char* Engine_ProcessUserInput_DLL = "Engine.dll";
inline constexpr const char* Engine_ProcessUserInput = "?ProcessUserInput@Engine@GAME@@QEAAXXZ";
// public: void __cdecl GAME::Display::Render(class GAME::GraphicsCanvas & __ptr64)const __ptr64
inline constexpr const char* Display_Render_DLL = "Engine.dll";
inline constexpr const char* Display_Render = "?Render@Display@GAME@@QEBAXAEAVGraphicsCanvas@2@@Z";
// public: void __cdecl GAME::Display::HandleKeyEvent(class GAME::InputDevice::ButtonEvent const & __ptr64) __ptr64
inline constexpr const char* Display_HandleKeyEvent_DLL = "Engine.dll";
inline constexpr const char* Display_HandleKeyEvent = "?HandleKeyEvent@Display@GAME@@QEAAXAEBVButtonEvent@InputDevice@2@@Z";
// public: void __cdecl GAME::Display::HandleMouseEvent(struct GAME::InputDevice::MouseEvent const & __ptr64) __ptr64
inline constexpr const char* Display_HandleMouseEvent_DLL = "Engine.dll";
inline constexpr const char* Display_HandleMouseEvent = "?HandleMouseEvent@Display@GAME@@QEAAXAEBUMouseEvent@InputDevice@2@@Z";
// public: unsigned short const * __ptr64 __cdecl GAME::InputDevice::ButtonEvent::GetText(void)const __ptr64
inline constexpr const char* ButtonEvent_GetText_DLL = "Engine.dll";
inline constexpr const char* ButtonEvent_GetText = "?GetText@ButtonEvent@InputDevice@GAME@@QEBAPEBGXZ";
// protected: bool __cdecl GAME::InputDevice::GetDefaultButtonName(enum GAME::InputDevice::Button,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > & __ptr
inline constexpr const char* InputDevice_GetDefaultButtonName_DLL = "Engine.dll";
inline constexpr const char* InputDevice_GetDefaultButtonName = "?GetDefaultButtonName@InputDevice@GAME@@IEBA_NW4Button@12@AEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z";
// public: virtual bool __cdecl GAME::DirectInputDevice::GetButtonName(enum GAME::InputDevice::Button,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > & _
inline constexpr const char* DirectInputDevice_GetButtonName_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_GetButtonName = "?GetButtonName@DirectInputDevice@GAME@@UEBA_NW4Button@InputDevice@2@AEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME::Graphics
inline constexpr const char* RenderText2d_XY_C_U16_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_XY_C_U16 = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::
inline constexpr const char* RenderText2d_XY_CC_U16_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_XY_CC_U16 = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@0PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,enum GAME::GraphicsXAlign,enum GAME:
inline constexpr const char* RenderText2d_Rect_C_U16_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_Rect_C_U16 = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@AEBVColor@2@PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,en
inline constexpr const char* RenderText2d_Rect_CC_U16_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_Rect_CC_U16 = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@AEBVColor@2@1PEBGPEBVGraphicsFont2@2@HW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontStyleFlag@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,enum GAME::Grap
inline constexpr const char* RenderText2d_XY_U16_FontName_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_XY_U16_FontName = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHPEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(int,int,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,float,enum GAME
inline constexpr const char* RenderText2d_XY_U16_FontName2_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_XY_U16_FontName2 = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXHHPEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MMW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2d(class GAME::Rect,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __ptr64,float,enum G
inline constexpr const char* RenderText2d_Rect_U16_FontName_DLL = "Engine.dll";
inline constexpr const char* RenderText2d_Rect_U16_FontName = "?RenderText2d@GraphicsCanvas@GAME@@QEAAXVRect@2@PEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@MW4GraphicsXAlign@2@W4GraphicsYAlign@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dBox(int,int,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class GAME::GraphicsFont2 const * __ptr64,int,bool,class GAME::Color const * __ptr64,enu
inline constexpr const char* RenderText2dBox_XY_C_U16_Font_DLL = "Engine.dll";
inline constexpr const char* RenderText2dBox_XY_C_U16_Font = "?RenderText2dBox@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBGPEBVGraphicsFont2@2@H_NPEBV32@W4FontStyleFlag@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dBox(int,int,class GAME::Color const & __ptr64,unsigned short const * __ptr64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > 
inline constexpr const char* RenderText2dBox_XY_C_U16_FontName_DLL = "Engine.dll";
inline constexpr const char* RenderText2dBox_XY_C_U16_FontName = "?RenderText2dBox@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@PEBGAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@M_NPEBV32@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderColoredText2d(int,int,class std::basic_string<unsigned short,struct std::char_traits<unsigned short>,class std::allocator<unsigned short> > const & __ptr64,class std::basi
inline constexpr const char* RenderColoredText2d_U16_DLL = "Engine.dll";
inline constexpr const char* RenderColoredText2d_U16 = "?RenderColoredText2d@GraphicsCanvas@GAME@@QEAAXHHAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@AEBVColor@2@W4FontLayout@2@@Z";
// public: void __cdecl GAME::GraphicsCanvas::RenderText2dParagraph(int,int,class GAME::Color const & __ptr64,class GAME::Color const & __ptr64,class mem::vector<class std::basic_string<unsigned short,struct std::char_trait
inline constexpr const char* RenderText2dParagraph_DLL = "Engine.dll";
inline constexpr const char* RenderText2dParagraph = "?RenderText2dParagraph@GraphicsCanvas@GAME@@QEAAXHHAEBVColor@2@0AEBV?$vector@V?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@mem@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z";
// public: virtual void __cdecl GAME::DirectInputDevice::AllowShortcutKeys(bool) __ptr64
inline constexpr const char* DirectInputDevice_AllowShortcutKeys_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_AllowShortcutKeys = "?AllowShortcutKeys@DirectInputDevice@GAME@@UEAAX_N@Z";
// private: static struct HHOOK__ * __ptr64 __ptr64 GAME::DirectInputDevice::keyboardHook
inline constexpr const char* DirectInputDevice_keyboardHook_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_keyboardHook = "?keyboardHook@DirectInputDevice@GAME@@0PEAUHHOOK__@@EA";
// public: virtual int __cdecl GAME::DirectInputDevice::GetNumKeyEvents(void)const __ptr64
inline constexpr const char* DirectInputDevice_GetNumKeyEvents_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_GetNumKeyEvents = "?GetNumKeyEvents@DirectInputDevice@GAME@@UEBAHXZ";
// public: virtual class GAME::InputDevice::ButtonEvent __cdecl GAME::DirectInputDevice::GetKeyEvent(int)const __ptr64
inline constexpr const char* DirectInputDevice_GetKeyEvent_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_GetKeyEvent = "?GetKeyEvent@DirectInputDevice@GAME@@UEBA?AVButtonEvent@InputDevice@2@H@Z";
// public: virtual int __cdecl GAME::DirectInputDevice::GetNumMouseEvents(void)const __ptr64
inline constexpr const char* DirectInputDevice_GetNumMouseEvents_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_GetNumMouseEvents = "?GetNumMouseEvents@DirectInputDevice@GAME@@UEBAHXZ";
// public: virtual __cdecl GAME::InputDevice::ButtonEvent::~ButtonEvent(void) __ptr64
inline constexpr const char* ButtonEvent_dtor_DLL = "Engine.dll";
inline constexpr const char* ButtonEvent_dtor = "??1ButtonEvent@InputDevice@GAME@@UEAA@XZ";
// public: __cdecl GAME::InputDevice::ButtonEvent::ButtonEvent(void) __ptr64
inline constexpr const char* ButtonEvent_ctor_DLL = "Engine.dll";
inline constexpr const char* ButtonEvent_ctor = "??0ButtonEvent@InputDevice@GAME@@QEAA@XZ";
// public: __cdecl GAME::InputDevice::MouseEvent::MouseEvent(void) __ptr64
inline constexpr const char* MouseEvent_ctor_DLL = "Engine.dll";
inline constexpr const char* MouseEvent_ctor = "??0MouseEvent@InputDevice@GAME@@QEAA@XZ";
// public: virtual bool __cdecl GAME::DirectInputDevice::IsButtonDown(enum GAME::InputDevice::Button)const __ptr64
inline constexpr const char* DirectInputDevice_IsButtonDown_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_IsButtonDown = "?IsButtonDown@DirectInputDevice@GAME@@UEBA_NW4Button@InputDevice@2@@Z";
// public: virtual class GAME::Vec2 __cdecl GAME::DirectInputDevice::GetCursorPosition(bool)const __ptr64
inline constexpr const char* DirectInputDevice_GetCursorPosition_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_GetCursorPosition = "?GetCursorPosition@DirectInputDevice@GAME@@UEBA?AVVec2@2@_N@Z";
// public: virtual struct GAME::InputDevice::MouseEvent __cdecl GAME::DirectInputDevice::GetMouseEvent(int)const __ptr64
inline constexpr const char* DirectInputDevice_GetMouseEvent_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_GetMouseEvent = "?GetMouseEvent@DirectInputDevice@GAME@@UEBA?AUMouseEvent@InputDevice@2@H@Z";
// private: static unsigned int GAME::DirectInputDevice::keyboardHookRefCount
inline constexpr const char* DirectInputDevice_keyboardHookRefCount_DLL = "DirectInput.dll";
inline constexpr const char* DirectInputDevice_keyboardHookRefCount = "?keyboardHookRefCount@DirectInputDevice@GAME@@0IA";
}  // namespace gd::names
