// Generated by tools/gen_riftgate_zones.py from database.arz -- do not edit. The riftgate map's zone list
// in the game's own (progression) order; act = the zone record's chunk letter (1a/1b/1f/1g/1h/1i/1j).
#pragma once
namespace gd::riftgate_zones {
struct Zone { const char* tag; int act; int order; };
inline constexpr Zone kZones[] = {
  {"tagRiftDevilsCrossing", 1, 0},   // riftgatemap1a_devilscrossing.dbr
  {"tagRiftLowerCrossing", 1, 1},   // riftgatemap1a_lowercrossing.dbr
  {"tagRiftBurrwitchRoad", 1, 2},   // riftgatemap1a_burrwitchroad.dbr
  {"tagRiftWightmire", 1, 3},   // riftgatemap1a_wightmire.dbr
  {"tagRiftFloodedPassage", 1, 4},   // riftgatemap1a_floodedpassage.dbr
  {"tagRiftBurrwitchOutskirts", 1, 5},   // riftgatemap1a_burrwitchoutskirts.dbr
  {"tagRiftBurrwitchVillage", 1, 6},   // riftgatemap1a_burrwitchvillage.dbr
  {"tagRiftWardensCellar", 1, 7},   // riftgatemap1a_wardenscellar.dbr
  {"tagRiftWardensLabratory01", 1, 8},   // riftgatemap1a_undergroundtransit.dbr
  {"tagRiftWardensLabratory02", 1, 9},   // riftgatemap1a_wardenslabratory.dbr
  {"tagRiftBrokenHills", 2, 10},   // riftgatemap1b_brokenhills.dbr
  {"tagRiftOldArkovia", 2, 11},   // riftgatemap1b_rockycoast.dbr
  {"tagRiftArkovianFoothills", 2, 12},   // riftgatemap1b_coastroad.dbr
  {"tagRiftTwinFalls", 2, 13},   // riftgatemap1b_twinfalls.dbr
  {"tagRiftCronleysHideout", 2, 14},   // riftgatemap1b_cronleyshideout.dbr
  {"tagRiftSmugglersPass", 2, 15},   // riftgatemap1b_smugglerspass.dbr
  {"tagRiftJaggedWaste", 2, 16},   // riftgatemap1b_jaggedwaste.dbr
  {"tagRiftDeadmansGulch", 2, 17},   // riftgatemap1b_deadmansgulch.dbr
  {"tagRiftSmugglersRoad", 2, 18},   // riftgatemap1b_highpass.dbr
  {"tagRiftHomestead", 3, 19},   // riftgatemap1f_homestead.dbr
  {"tagRiftRottedCroplands", 3, 20},   // riftgatemap1f_witheringfields.dbr
  {"tagRiftSorrowsBastion", 3, 21},   // riftgatemap1f_sorrowsbastion.dbr
  {"tagRiftBloodGrove", 3, 22},   // riftgatemap1f_bloodgrove.dbr
  {"tagRiftDarkvale", 3, 23},   // riftgatemap1f_darkvale.dbr
  {"tagRiftAlpineGate", 4, 24},   // riftgatemap1g_alpinegate.dbr
  {"tagRiftAlpineRoad", 4, 25},   // riftgatemap1g_alpineroad.dbr
  {"tagRiftAlpineValley", 4, 26},   // riftgatemap1g_alpinevalley.dbr
  {"tagRiftAlpineFort", 4, 27},   // riftgatemap1g_alpinefort.dbr
  {"tagRiftNecropolisGate", 4, 28},   // riftgatemap1g_necropolisgate.dbr
  {"tagRiftNecropolisInterior", 4, 29},   // riftgatemap1g_necropolisinterior.dbr
  {"tagGDX1RiftGloomwaldEntrance", 5, 30},   // riftgatemap1h_darkforestentrance.dbr
  {"tagGDX1RiftGloomwaldRiverCrossing", 5, 31},   // riftgatemap1h_darkforestrivercrossing.dbr
  {"tagGDX1RiftUgdenbogCoven", 5, 32},   // riftgatemap1h_ugdenbogcoven.dbr
  {"tagGDX1RiftUgdenbogCenter", 5, 33},   // riftgatemap1h_ugdenbogcenter.dbr
  {"tagGDX1RiftUgdenbogVillage", 5, 34},   // riftgatemap1h_ugdenbogvillage.dbr
  {"tagGDX1RiftMalmouthAetherfire", 6, 35},   // riftgatemap1i_aetherfire.dbr
  {"tagGDX1RiftMalmouthOutskirts", 6, 36},   // riftgatemap1i_malmouthoutskirts.dbr
  {"tagGDX1RiftMalmouthSewers", 6, 37},   // riftgatemap1i_malmouthsewer.dbr
  {"tagGDX1RiftMalmouthIndustrial", 6, 38},   // riftgatemap1i_malmouthindustrial.dbr
  {"tagGDX1RiftMalmouthInner", 6, 39},   // riftgatemap1i_malmouthinner.dbr
  {"tagGDX2RiftWitchGodBase", 7, 40},   // riftgatemap1j_witchgodbase.dbr
  {"tagGDX2RiftKorvanPlateau", 7, 41},   // riftgatemap1j_korvanplateau.dbr
  {"tagGDX2RiftKorvanSands", 7, 42},   // riftgatemap1j_korvansands.dbr
  {"tagGDX2RiftCairanDocks", 7, 43},   // riftgatemap1j_cairandocks.dbr
  {"tagGDX2RiftOasis", 7, 44},   // riftgatemap1j_sunbaneoasis.dbr
  {"tagGDX2RiftVanguard", 7, 45},   // riftgatemap1j_vanguard.dbr
  {"tagGDX2RiftInfernalWastes", 7, 46},   // riftgatemap1j_infernalwastes.dbr
  {"tagGDX2RiftKorvanCity", 7, 47},   // riftgatemap1j_korvancity.dbr
  {"tagGDX2RiftTemple", 7, 48},   // riftgatemap1j_korvaaktomb.dbr
  {"tagGDX2RiftEldritch", 7, 49},   // riftgatemap1j_astralfields.dbr
  {"tagGDX2RiftTempleOfOsyr", 7, 50},   // riftgatemap1j_templeofosyr.dbr
  {"tagGDX2RiftAbyd", 7, 51},   // riftgatemap1j_ruinsofabyd.dbr
  {"tagGDX2RiftLostOasis", 7, 52},   // riftgatemap1j_lostoasis.dbr
};
inline constexpr int kActs = 7;
}  // namespace gd::riftgate_zones
